### PR TITLE
Allow the amixer mixer name to be changed

### PR DESCRIPTION
**Pull request by zdykstra**
This allows amixer to report the PulseAudio default mixer volume. Both example configuration files have been updated to reflect the proposed change.

### CODE REVIEW

**Comment by davidscholberg** [comment]
@zdykstra Thank you for another pull request!

I do have a couple of changes to request:

1. I think `mixer_device` is a more descriptive name for this new config option.
1. I always try as much as is practical to maintain backwards compatibility with existing configs, such that updating goblocks doesn't require people to also update their configs. As such, I think that the code should set a default value of "default" for the new config option so that goblocks doesn't break for people that are already using the volume block.

Let me know what you think of these requested changes.

**Comment by zdykstra** [comment]
I agree with both points - updated as requested!

**Comment by davidscholberg** [comment]
Thanks for the updates!

I'm going to merge this into the `pulseaudio` branch on my repo first, because I want to also make the ALSA channel a configurable variable, and I want to release all of these changes to master at the same time. I'll comment on this merge request when all of this gets merged to master.

Thanks again for your contribution!

**Comment by davidscholberg** [comment]
@zdykstra your changes have been merged into master in #13.

**Pull request merged**
